# Generated by Django 4.2.15 on 2024-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL"
            ),
        ),
    ]
