# Generated by Django 4.2.15 on 2024-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0002_store_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="images/"
            ),
        ),
    ]
