# Generated by Django 4.2.15 on 2024-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0003_store_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="time_update",
        ),
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(default="Описание отсутствует"),
        ),
        migrations.AddField(
            model_name="store",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="store",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
