# Generated by Django 4.2.15 on 2024-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0004_remove_store_time_update_store_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(default="Описание отсутствует")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("slug", models.SlugField(unique=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="store",
            name="description",
        ),
        migrations.RemoveField(
            model_name="store",
            name="image",
        ),
        migrations.RemoveField(
            model_name="store",
            name="price",
        ),
        migrations.AddField(
            model_name="store",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="store",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
