# Generated by Django 4.2.15 on 2024-09-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0005_product_remove_store_description_remove_store_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="asia.store",
            ),
        ),
    ]
