# Generated by Django 4.2.15 on 2024-10-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0009_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
