# Generated by Django 4.2.15 on 2024-10-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0011_category_product_category_store_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="time_create",
        ),
        migrations.RemoveField(
            model_name="category",
            name="time_update",
        ),
        migrations.RemoveField(
            model_name="store",
            name="categories",
        ),
        migrations.AddField(
            model_name="store",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="asia.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
