# Generated by Django 4.2.15 on 2024-10-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0012_remove_category_time_create_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="store",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
