# Generated by Django 4.2.15 on 2024-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0014_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="uncategorized", max_length=50),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
