# Generated by Django 4.2.15 on 2024-10-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asia", "0015_alter_product_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
